### ISSUE TITLE
String and Text properties are stored in DataStore as encoded Blob

### ISSUE THREAD

**Issue by JorinTielen** [Bogdanp/anom-py#12]
So as the title says, currently String properties get stored as encoded Blobs in the Datastore, which makes them unreadable in the cloud console Datastore viewer. This also makes doing anything with your data outside of anom more difficult. Storing Strings as Strings is probably a more sane default.

Now i know this is because there is compression support for Text properties, but having Strings as default, with encoding being optional, makes more sense in my opinion.

I made a quick refactor on [my fork](https://github.com/JorinTielen/anom-py/commit/b55ebc7b139bbf3831b940770e4d27906c76895b) (which also just removes compression from Text). As that is breaking you probably aren't interested in merging that (if you are, i can make a PR :) ).

**Comment by Bogdanp** [comment]
How about a compromise? I'd accept a PR that adds a new type (`Unicode` or something) with these semantics. That way we won't break backwards-compatibility.

**Comment by Bogdanp** [comment]
Thanks! This is released in `0.8.0`.
