### ISSUE TITLE
Unique index support on properties

### ISSUE THREAD

**Issue by jnoortheen** [Bogdanp/anom-py#17]
I know the limitation of datastore. But it is handy to have a way to enforce uniqueness on the properties. Here [djangae](https://github.com/potatolondon/djangae.git) has implemented a custom way to apply this. Is it possible to do the same here?

**Comment by Bogdanp** [comment]
Sorry! I missed this when it was first opened. I want to avoid emulating things that Datastore doesn't natively support so users don't shoot themselves in their respective feet.
