### ISSUE TITLE
Key.get() namespace `None` overwrite with global namespace leads to Key mismatch 

### ISSUE THREAD

**Issue by AndreCimander** [Bogdanp/anom-py#9]
First of all: thanks for creating and maintaining this package! :+1: 

Sadly I haven't found the time to debug it properly due to crunch time.

`key_from_protobuf` in google.cloud.datastore.helpers creates a Key with a None-value namespace, but anom replaces a None namespace with the global default namespace (which is an empty string), resulting in a ValueError:

```
        for entity in found:
>           index = datastore_keys.index(entity.key)
E           ValueError: <Key('SocialMediaAuth', 'test1'), project='xxx'> is not in list

../../../../library/anom/adapter.py:147: ValueError
```

My current workaround is setting the default namespace to None, which requires two line changes in anom.namespaces. I haven't fully validated that this doesn't cause other issues, I'll update this issue if we run into other problems, maybe you have some feedback about this workaround :)

Packages:
```
anom==0.7
google-cloud==0.32.0
google-cloud-datastore==1.0.0 (also an issue with 1.6.0)
```

**Comment by Bogdanp** [comment]
Thanks for the report! Does this happen consistently? Is there any chance you could reduce this down to a small, reproducible example? I've tried to reproduce the issue with the following script to no avail:

```python
import anom
from anom import Model, props


class Foo(Model):
    x = props.Integer()


f = Foo(x=42).put()

# I'd've expected at least one of these to fail:
f.key.get()
anom.get_multi([f.key] * 10)
Foo.query().run()
```

The case you mentioned *should* be correctly handled by this code:

```python
    def _convert_key_to_datastore(self, anom_key):
        return self.client.key(*anom_key.path, namespace=anom_key.namespace or None)
```

I.e. all `datastore_keys` without a namespace should have their namespace converted to none before that `index()` check so this is very strange! :D

**Comment by AndreCimander** [comment]
And you are correct, `_convert_key_to_datastore` does indeed handle it.

Some genius subclassed the adapter and forgot to update it ... git-blame tells me this genius has the same name as I do ... what a coincidence :see_no_evil: 

Sorry for wasting your time!

**Comment by Bogdanp** [comment]
Hah! No worries!
